#!/bin/bash
# autopilot-constants.sh — 脚本共享常量
#
# 允许通过环境变量覆盖，避免硬编码漂移。

: "${LOW_CONTEXT_THRESHOLD:=25}"
: "${LOW_CONTEXT_CRITICAL_THRESHOLD:=15}"
: "${IDLE_THRESHOLD:=300}"
: "${IDLE_CONFIRM_PROBES:=3}"
: "${WORKING_INERTIA_SECONDS:=90}"
: "${LAYER2_FILE_PREVIEW_LIMIT:=20}"
: "${LAYER2_FALLBACK_COMMIT_WINDOW:=30}"
: "${TSC_TIMEOUT_SECONDS:=30}"
: "${REVIEW_OUTPUT_WAIT_SECONDS:=90}"
